sudo: required
language: python
python:
    - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install libboost-python-dev libboost-all-dev

services:
    - docker

env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32

install:
    - docker pull $DOCKER_IMAGE
#    - export CFLAGS='-g -O0 --coverage'

script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.travis/build-wheels.sh
    - ls wheelhouse/

after_success:
- echo 'Done'
# TODO: Upload wheels